server:
  port: 8003

# 服务与服务之间相互调用一般都是根据这个name 。
spring:
  application:
    name: user-service

eureka:
  client:
    serviceUrl:
      #      指定服务注册中心的地址
      defaultZone: http://localhost:8001/eureka/


#  feign继承了hystrix，但是默认没有开启，所以我们要在配置文件中开启hystrix功能：
#启用hystrix
feign:
  hystrix:
    enabled: true
